#include <furi.h>
#include <gui/gui.h>
#include <gui/icon_i.h>
#include <gui/view_dispatcher.h>
#include <gui/scene_manager.h>
#include <gui/modules/menu.h>
#include <gui/modules/popup.h>
#include <gui/modules/submenu.h>
/* generated by fbt from .png files in images folder */
#include <caesarify_icons.h>

#define TAG "caesarify"

// -------------- Big Enum Lobby Interests ---------------
typedef enum {
    CaesarScene_MainMenu, // scene 1
    CaesarScene_CheckCardType, // scene 2
    CaesarScene_WriteContents, // scene 3
    CaesarScene_About, // scene 4
    CaesarScene_count // amount of scenes
} caesar_app_scene;

// Index of menus used by the app
typedef enum {
    CaesarView_Menu, // menu type view
    CaesarView_Popup, // popup type view
    CaesarView_SubMenu
} caesar_app_view;

// the app context struct, creates stuff app needs
typedef struct {
    SceneManager* scene_manager;
    ViewDispatcher* view_dispatcher;
    Menu* menu;
    Popup* popup;
    Submenu* submenu;
} Caesarify;

// custom events enum
typedef enum {
    CaesarEvent_ShowCheckCardType,
    CaesarEvent_ShowWriteContents,
    CaesarEvent_ShowAbout
} CaesarEvent;

// indicies for the menu items
typedef enum {
    CaesarMenuSelection_CheckCardType,
    CaesarMenuSelection_WriteContents,
    CaesarMenuSelection_About
} CaesarMenuSelection;

// ------------------ Main Menu ------------------------
void caesar_menu_callback_main_menu(void* context, uint32_t index) {
    FURI_LOG_T(TAG, "menu_callback_main_menu");
    Caesarify* app = context;
    switch(index) {
        // if first option
    case CaesarMenuSelection_CheckCardType:
        scene_manager_handle_custom_event(app->scene_manager, CaesarEvent_ShowCheckCardType);
        break;
        // if second option
    case CaesarMenuSelection_WriteContents:
        scene_manager_handle_custom_event(app->scene_manager, CaesarEvent_ShowWriteContents);
        break;
    case CaesarMenuSelection_About:
        scene_manager_handle_custom_event(app->scene_manager, CaesarEvent_ShowAbout);
    }
}

// resets menu, gives content, callbacks, and selections
void caesar_scene_on_enter_main_menu(void* context) {
    FURI_LOG_T(TAG, "caesar_scene_on_enter_main_menu");
    Caesarify* app = context;
    menu_reset(app->menu);

    // icons are null, because i dont have any animated icons, if an icon does not have a framerate, we end up dividing by zero
    // i may convert this to a submenu at some point, but animated icons seem too cool of an opportunity to pass up if they work
    menu_add_item(
        app->menu,
        "Check Card Type", // Label
        NULL, // icon would go here
        CaesarMenuSelection_CheckCardType, // enum value provided to callback function as an index (what option was selected)
        caesar_menu_callback_main_menu, // callback function if selected
        app);

    menu_add_item(
        app->menu,
        "Write Contents",
        NULL,
        CaesarMenuSelection_WriteContents,
        caesar_menu_callback_main_menu,
        app);

    menu_add_item(
        app->menu, "About", NULL, CaesarMenuSelection_About, caesar_menu_callback_main_menu, app);
    view_dispatcher_switch_to_view(app->view_dispatcher, CaesarView_Menu);
}

// main menu event handler, switches scene based on the event
bool caesar_scene_on_event_main_menu(void* context, SceneManagerEvent event) {
    FURI_LOG_T(TAG, "caesar_scene_on_event_main_menu");
    Caesarify* app = context;
    bool consumed = false;
    switch(event.type) {
    case SceneManagerEventTypeCustom:
        switch(event.event) {
        case CaesarEvent_ShowCheckCardType:
            scene_manager_next_scene(app->scene_manager, CaesarScene_CheckCardType);
            consumed = true;
            break;
        case CaesarEvent_ShowWriteContents:
            scene_manager_next_scene(app->scene_manager, CaesarScene_WriteContents);
            consumed = true;
            break;
        case CaesarEvent_ShowAbout:
            scene_manager_next_scene(app->scene_manager, CaesarScene_About);
            break;
        }
        break;
    default:
        consumed = false;
        break;
    }
    return consumed;
}
void caesar_scene_on_exit_main_menu(void* context) {
    FURI_LOG_T(TAG, "scene_on_exit_main_menu");
    Caesarify* app = context;
    menu_reset(app->menu);
}

// -------------------- Menu 1 scene ---------------------------
void caesar_scene_on_enter_check_card_type(void* context) {
    FURI_LOG_T(TAG, "scene_on_enter_check_card_type");
    Caesarify* app = context;
    popup_reset(app->popup);
    popup_set_context(app->popup, app);
    popup_set_header(app->popup, "Reading", 80, 10, AlignCenter, AlignTop);
    popup_set_text(
        app->popup, "Hold the\nunknown card to\nFlipper's back", 80, 25, AlignCenter, AlignTop);
    popup_enable_timeout(app->popup);
    popup_set_timeout(app->popup, 300);
    view_dispatcher_switch_to_view(app->view_dispatcher, CaesarView_Popup);
    FURI_LOG_T(TAG, "switching to view");
}

bool caesar_scene_on_event_check_card_type(void* context, SceneManagerEvent event) {
    FURI_LOG_T(TAG, "scene_on_event_check_card_type");
    UNUSED(context);
    UNUSED(event);
    return false;
}

void caesar_scene_on_exit_check_card_type(void* context) {
    FURI_LOG_T(TAG, "scene_on_exit_check_card_type");
    Caesarify* app = context;
    popup_reset(app->popup);
}

// -------------------- Menu 2 scene ---------------------------
void caesar_scene_on_enter_show_write_contents(void* context) {
    FURI_LOG_T(TAG, "caesar_scene_on_enter_show_write_contents");
    Caesarify* app = context;
    submenu_reset(app->submenu);
    submenu_add_item(app->submenu, "Caesarify", 0, caesar_menu_callback_main_menu, app);
    submenu_add_item(app->submenu, "Custom Content", 1, caesar_menu_callback_main_menu, app);
    view_dispatcher_switch_to_view(app->view_dispatcher, CaesarView_SubMenu);
}

bool caesar_scene_on_event_show_write_contents(void* context, SceneManagerEvent event) {
    FURI_LOG_T(TAG, "scene_on_event_show_write_contents");
    UNUSED(context);
    UNUSED(event);
    return false;
}

void caesar_scene_on_exit_show_write_contents(void* context) {
    FURI_LOG_T(TAG, "scene_on_exit_show_write_contents");
    Caesarify* app = context;
    submenu_reset(app->submenu);
}

// about page scene
void caesar_scene_on_enter_about(void* context) {
    FURI_LOG_T(TAG, "scene_on_enter_about");
    Caesarify* app = context;
    popup_reset(app->popup);
    popup_set_context(app->popup, context);
    popup_set_header(app->popup, "Caesarify", 30, 0, AlignCenter, AlignTop);
    popup_set_text(
        app->popup,
        "App created\nby @mochabeau,\nwith art from\n my bf\n @goatogen",
        90,
        5,
        AlignCenter,
        AlignTop);
    view_dispatcher_switch_to_view(app->view_dispatcher, CaesarView_Popup);
}

bool caesar_scene_on_event_about(void* context, SceneManagerEvent event) {
    FURI_LOG_T(TAG, "scene_on_event_about");
    UNUSED(context);
    UNUSED(event);
    return false;
}

void caesar_scene_on_exit_about(void* context) {
    FURI_LOG_T(TAG, "on_exit_about");
    Caesarify* app = context;
    popup_reset(app->popup);
}

// collection of all scene on ENTER handlers
void (*const caesar_scene_on_enter_handlers[])(void*) = {
    caesar_scene_on_enter_main_menu,
    caesar_scene_on_enter_check_card_type,
    caesar_scene_on_enter_show_write_contents,
    caesar_scene_on_enter_about};

// collection of all scene on EVENT handlers
bool (*const caesar_scene_on_event_handlers[])(void*, SceneManagerEvent) = {
    caesar_scene_on_event_main_menu,
    caesar_scene_on_event_check_card_type,
    caesar_scene_on_event_show_write_contents,
    caesar_scene_on_event_about};

// collection of all scene on EXIT handlers
void (*const caesar_scene_on_exit_handlers[])(void*) = {
    caesar_scene_on_exit_main_menu,
    caesar_scene_on_exit_check_card_type,
    caesar_scene_on_exit_show_write_contents,
    caesar_scene_on_exit_about};

// collection of all on_enter, on_event, on_exit handlers
const SceneManagerHandlers caesar_scene_event_handlers = {
    .on_enter_handlers = caesar_scene_on_enter_handlers,
    .on_event_handlers = caesar_scene_on_event_handlers,
    .on_exit_handlers = caesar_scene_on_exit_handlers,
    .scene_num = CaesarScene_count};

bool caesar_scene_manager_custom_event_callback(void* context, uint32_t custom_event) {
    FURI_LOG_T(TAG, "caesar_event_manager_custom_event_callback");
    furi_assert(context);
    Caesarify* app = context;
    return scene_manager_handle_custom_event(app->scene_manager, custom_event);
}

bool caesar_scene_manager_navigation_event_callback(void* context) {
    FURI_LOG_T(TAG, "scene_manager_navigation_event_callback");
    furi_assert(context);
    Caesarify* app = context;
    return scene_manager_handle_back_event(app->scene_manager);
}

// allocates memory for the scene thing
void caesar_scene_manager_init(Caesarify* app) {
    FURI_LOG_T(TAG, "allocating memory for scene manager");
    app->scene_manager = scene_manager_alloc(&caesar_scene_event_handlers, app);
}

void caesar_view_dispatcher_init(Caesarify* app) {
    FURI_LOG_T(TAG, "allocating memory for view dispatcher");
    app->view_dispatcher = view_dispatcher_alloc();

    FURI_LOG_D(TAG, "view_dispatcher_init is now allocating views");
    app->menu = menu_alloc();
    app->popup = popup_alloc();
    app->submenu = submenu_alloc();

    // assigns callback that passes events from views to the scene manager
    view_dispatcher_set_event_callback_context(app->view_dispatcher, app);
    view_dispatcher_set_custom_event_callback(
        app->view_dispatcher, caesar_scene_manager_custom_event_callback);
    view_dispatcher_set_navigation_event_callback(
        app->view_dispatcher, caesar_scene_manager_navigation_event_callback);

    // add views to the view dispatcher, indexed by the enum.
    view_dispatcher_add_view(app->view_dispatcher, CaesarView_Menu, menu_get_view(app->menu));
    view_dispatcher_add_view(app->view_dispatcher, CaesarView_Popup, popup_get_view(app->popup));
    view_dispatcher_add_view(
        app->view_dispatcher, CaesarView_SubMenu, submenu_get_view(app->submenu));
}

Caesarify* caesarify_init() {
    FURI_LOG_I("caesar_start", "Pizza, Pizza!");
    Caesarify* app = malloc(sizeof(Caesarify));
    caesar_scene_manager_init(app); // start init of scene manager
    caesar_view_dispatcher_init(app); // start init of view dispatcher
    return app;
}

// frees everything from RAM
void caesarify_free(Caesarify* app) {
    FURI_LOG_T(TAG, "caesarify freeing memory...");
    scene_manager_free(
        app->scene_manager); // should free all scene because they're enumed together
    view_dispatcher_remove_view(app->view_dispatcher, CaesarView_Menu);
    view_dispatcher_remove_view(app->view_dispatcher, CaesarView_Popup);
    view_dispatcher_remove_view(app->view_dispatcher, CaesarView_SubMenu);
    view_dispatcher_free(app->view_dispatcher);
    menu_free(app->menu);
    popup_free(app->popup);
    submenu_free(app->submenu);
    free(app);
}

void set_log_level() {
    // #ifdef FURI_DEBUG
    furi_log_set_level(FuriLogLevelTrace);
    // #else
    //    furi_log_set_level(FuriLogLevelInfo);
    // #endif
}

int32_t caesarify_app(void* p) {
    UNUSED(p);
    set_log_level();

    FURI_LOG_I(TAG, "Starting Caesarify...");
    Caesarify* app = caesarify_init();

    Gui* gui = furi_record_open(RECORD_GUI);
    view_dispatcher_attach_to_gui(app->view_dispatcher, gui, ViewDispatcherTypeFullscreen);
    scene_manager_next_scene(app->scene_manager, CaesarScene_MainMenu);
    FURI_LOG_D(TAG, "Starting dispatcher...");
    view_dispatcher_run(app->view_dispatcher);

    // free all memory
    FURI_LOG_I(TAG, "Caesarify closing...");
    furi_record_close(RECORD_GUI);
    caesarify_free(app);
    return 0;
}
