#include <furi.h>
#include <gui/gui.h>
#include <gui/icon_i.h>
#include <gui/view_dispatcher.h>
#include <gui/scene_manager.h>
#include <gui/modules/menu.h>
#include <gui/modules/popup.h>
/* generated by fbt from .png files in images folder */
#include <caesarify_icons.h>

#define TAG "caesarify"

typedef enum {
    CaesarScene_MainMenu, // scene 1
    CaesarScene_FirstPopup, // scene 2
    CaesarScene_SecondPopup,
    CaesarAppScene_count
} TestAppScene;

typedef enum {
    TestAppView_Menu,
    TestAppView_Popup
} TestAppView;

// allocates memory for the scene thing
void caesar_app_scene_pizza_init() {
    app->scene_manager = scene_manager_alloc(&caesar_app_scene_event_pizza, app);
}

int32_t caesarify_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "I'm caesarify!");
    CaesarApp* app = malloc(sizeof(CaesarApp));
    caesar_app_scene_pizza_init(app); // start init of scene manager
    caesar_app_view_pizza_init(app); // start init of view dispatcher

    return 0;
}
